WITH bounds AS (

    SELECT
        MIN(TO_DATE(ORDER_DATE)) AS MIN_DATE,
        MAX(TO_DATE(ORDER_DATE)) AS MAX_DATE
    FROM {{ ref('stg_orders') }}

),

numbers AS (

    SELECT
        SEQ4() AS N
    FROM TABLE(GENERATOR(ROWCOUNT => 3660))

),

date_spine AS (

    SELECT
        DATEADD(DAY, N, MIN_DATE) AS FULL_DATE
    FROM bounds
    CROSS JOIN numbers
    WHERE DATEADD(DAY, N, MIN_DATE) <= MAX_DATE

)

SELECT
    TO_NUMBER(TO_CHAR(FULL_DATE, 'YYYYMMDD')) AS DATE_KEY,
    FULL_DATE,
    YEAR(FULL_DATE) AS YEAR,
    QUARTER(FULL_DATE) AS QUARTER,
    MONTH(FULL_DATE) AS MONTH,
    MONTHNAME(FULL_DATE) AS MONTH_NAME,
    WEEKOFYEAR(FULL_DATE) AS WEEK_OF_YEAR,
    DAY(FULL_DATE) AS DAY_OF_MONTH,
    DAYOFWEEK(FULL_DATE) AS DAY_OF_WEEK,
    DAYNAME(FULL_DATE) AS DAY_NAME,
    CASE
        WHEN DAYOFWEEK(FULL_DATE) IN (1, 7)
            THEN TRUE
        ELSE FALSE
    END AS IS_WEEKEND
FROM date_spine