SELECT
    MD5(TO_VARCHAR(OI.ORDER_ITEM_ID)) AS SALES_KEY,

    OI.ORDER_ITEM_ID,
    O.ORDER_ID,

    TO_NUMBER(
        TO_CHAR(TO_DATE(O.ORDER_DATE), 'YYYYMMDD')
    ) AS DATE_KEY,

    MD5(TO_VARCHAR(O.CUSTOMER_ID)) AS CUSTOMER_KEY,

    MD5(TO_VARCHAR(OI.PRODUCT_ID)) AS PRODUCT_KEY,

    MD5(TO_VARCHAR(O.STORE_ID)) AS STORE_KEY,

    O.ORDER_DATE,
    O.ORDER_STATUS,
    O.PAYMENT_METHOD,

    OI.QUANTITY,
    OI.UNIT_PRICE,
    OI.DISCOUNT,

    OI.QUANTITY * OI.UNIT_PRICE AS GROSS_AMOUNT,

    OI.DISCOUNT AS DISCOUNT_AMOUNT,

    (OI.QUANTITY * OI.UNIT_PRICE) - OI.DISCOUNT AS NET_AMOUNT,

    OI.LINE_AMOUNT AS SOURCE_LINE_AMOUNT

FROM {{ ref('stg_order_items') }} OI

INNER JOIN {{ ref('stg_orders') }} O
    ON OI.ORDER_ID = O.ORDER_ID