SELECT
    P.PRODUCT_KEY,
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.SUBCATEGORY,
    P.BRAND,

    COUNT(DISTINCT F.ORDER_ID) AS TOTAL_ORDERS,

    SUM(F.QUANTITY) AS TOTAL_QUANTITY,

    SUM(F.GROSS_AMOUNT) AS GROSS_SALES,

    SUM(F.DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT,

    SUM(F.NET_AMOUNT) AS NET_SALES,

    ROUND(
        SUM(F.NET_AMOUNT) / NULLIF(SUM(F.QUANTITY), 0),
        2
    ) AS AVERAGE_SELLING_PRICE

FROM {{ ref('fact_sales') }} F

INNER JOIN {{ ref('dim_product') }} P
    ON F.PRODUCT_KEY = P.PRODUCT_KEY

GROUP BY
    P.PRODUCT_KEY,
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.SUBCATEGORY,
    P.BRAND