SELECT
    C.CUSTOMER_KEY,
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CITY,
    C.STATE,
    C.COUNTRY,

    COUNT(DISTINCT F.ORDER_ID) AS TOTAL_ORDERS,

    SUM(F.QUANTITY) AS TOTAL_QUANTITY,

    SUM(F.GROSS_AMOUNT) AS GROSS_SALES,

    SUM(F.DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT,

    SUM(F.NET_AMOUNT) AS NET_SALES,

    ROUND(
        SUM(F.NET_AMOUNT) / NULLIF(COUNT(DISTINCT F.ORDER_ID), 0),
        2
    ) AS AVERAGE_ORDER_VALUE,

    MIN(F.ORDER_DATE) AS FIRST_ORDER_DATE,

    MAX(F.ORDER_DATE) AS LAST_ORDER_DATE

FROM {{ ref('fact_sales') }} F

INNER JOIN {{ ref('dim_customer') }} C
    ON F.CUSTOMER_KEY = C.CUSTOMER_KEY

GROUP BY
    C.CUSTOMER_KEY,
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CITY,
    C.STATE,
    C.COUNTRY