SELECT
    D.FULL_DATE,

    COUNT(DISTINCT F.ORDER_ID) AS TOTAL_ORDERS,

    COUNT(F.ORDER_ITEM_ID) AS TOTAL_ORDER_ITEMS,

    SUM(F.QUANTITY) AS TOTAL_QUANTITY,

    SUM(F.GROSS_AMOUNT) AS GROSS_SALES,

    SUM(F.DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT,

    SUM(F.NET_AMOUNT) AS NET_SALES,

    ROUND(
        SUM(F.NET_AMOUNT) / NULLIF(COUNT(DISTINCT F.ORDER_ID), 0),
        2
    ) AS AVERAGE_ORDER_VALUE

FROM {{ ref('fact_sales') }} F

INNER JOIN {{ ref('dim_date') }} D
    ON F.DATE_KEY = D.DATE_KEY

GROUP BY
    D.FULL_DATE