SELECT
    S.STORE_KEY,
    S.STORE_ID,
    S.STORE_NAME,
    S.CITY,
    S.STATE,
    S.REGION,
    S.STORE_TYPE,

    COUNT(DISTINCT F.ORDER_ID) AS TOTAL_ORDERS,

    SUM(F.QUANTITY) AS TOTAL_QUANTITY,

    SUM(F.GROSS_AMOUNT) AS GROSS_SALES,

    SUM(F.DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT,

    SUM(F.NET_AMOUNT) AS NET_SALES,

    ROUND(
        SUM(F.NET_AMOUNT) / NULLIF(COUNT(DISTINCT F.ORDER_ID), 0),
        2
    ) AS AVERAGE_ORDER_VALUE

FROM {{ ref('fact_sales') }} F

INNER JOIN {{ ref('dim_store') }} S
    ON F.STORE_KEY = S.STORE_KEY

GROUP BY
    S.STORE_KEY,
    S.STORE_ID,
    S.STORE_NAME,
    S.CITY,
    S.STATE,
    S.REGION,
    S.STORE_TYPE