--To verify/check row counts of the tables
select table_name, row_count
from retail_db.information_schema.tables
where table_schema = 'RAW'
and table_name in (
    'CUSTOMERS',
    'ORDERS',
    'ORDER_ITEMS',
    'PAYMENTS',
    'PRODUCTS',
    'STORES'
);

SELECT * FROM RETAIL_DB.RAW.CUSTOMERS LIMIT 5;

SELECT * FROM RETAIL_DB.RAW.PRODUCTS LIMIT 5;

SELECT * FROM RETAIL_DB.RAW.STORES LIMIT 5;

SELECT * FROM RETAIL_DB.RAW.ORDERS LIMIT 5;

SELECT * FROM RETAIL_DB.RAW.ORDER_ITEMS LIMIT 5;

SELECT * FROM RETAIL_DB.RAW.PAYMENTS LIMIT 5;

USE DATABASE RETAIL_DB;
USE SCHEMA RAW;

-- =====================================================
-- 1. Check NULL primary/business keys
-- =====================================================

SELECT 'CUSTOMERS' AS TABLE_NAME, COUNT(*) AS NULL_KEY_COUNT
FROM CUSTOMERS
WHERE CUSTOMER_ID IS NULL

UNION ALL

SELECT 'PRODUCTS', COUNT(*)
FROM PRODUCTS
WHERE PRODUCT_ID IS NULL

UNION ALL

SELECT 'STORES', COUNT(*)
FROM STORES
WHERE STORE_ID IS NULL

UNION ALL

SELECT 'ORDERS', COUNT(*)
FROM ORDERS
WHERE ORDER_ID IS NULL

UNION ALL

SELECT 'ORDER_ITEMS', COUNT(*)
FROM ORDER_ITEMS
WHERE ORDER_ITEM_ID IS NULL

UNION ALL

SELECT 'PAYMENTS', COUNT(*)
FROM PAYMENTS
WHERE PAYMENT_ID IS NULL;

-- =====================================================
-- 2. Check duplicate primary keys
-- =====================================================

SELECT 'CUSTOMERS' AS TABLE_NAME,
       COUNT(*) - COUNT(DISTINCT CUSTOMER_ID) AS DUPLICATE_COUNT
FROM CUSTOMERS

UNION ALL

SELECT 'PRODUCTS',
       COUNT(*) - COUNT(DISTINCT PRODUCT_ID)
FROM PRODUCTS

UNION ALL

SELECT 'STORES',
       COUNT(*) - COUNT(DISTINCT STORE_ID)
FROM STORES

UNION ALL

SELECT 'ORDERS',
       COUNT(*) - COUNT(DISTINCT ORDER_ID)
FROM ORDERS

UNION ALL

SELECT 'ORDER_ITEMS',
       COUNT(*) - COUNT(DISTINCT ORDER_ITEM_ID)
FROM ORDER_ITEMS

UNION ALL

SELECT 'PAYMENTS',
       COUNT(*) - COUNT(DISTINCT PAYMENT_ID)
FROM PAYMENTS;

-- =====================================================
-- 3. Check invalid foreign keys
-- =====================================================

-- Orders → Customers
SELECT COUNT(*) AS INVALID_CUSTOMER_ID
FROM ORDERS O
LEFT JOIN CUSTOMERS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;


-- Orders → Stores
SELECT COUNT(*) AS INVALID_STORE_ID
FROM ORDERS O
LEFT JOIN STORES S
    ON O.STORE_ID = S.STORE_ID
WHERE S.STORE_ID IS NULL;


-- Order Items → Orders
SELECT COUNT(*) AS INVALID_ORDER_ID
FROM ORDER_ITEMS OI
LEFT JOIN ORDERS O
    ON OI.ORDER_ID = O.ORDER_ID
WHERE O.ORDER_ID IS NULL;


-- Order Items → Products
SELECT COUNT(*) AS INVALID_PRODUCT_ID
FROM ORDER_ITEMS OI
LEFT JOIN PRODUCTS P
    ON OI.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL;


-- Payments → Orders
SELECT COUNT(*) AS INVALID_PAYMENT_ORDER_ID
FROM PAYMENTS P
LEFT JOIN ORDERS O
    ON P.ORDER_ID = O.ORDER_ID
WHERE O.ORDER_ID IS NULL;